SELECT * FROM Demo;
SELECT id FROM Demo;
SELECT COUNT(ID) FROM Demo;
SELECT MAX(ID) As Max_ID, ID FROM Demo;

SELECT * FROM Demo WHERE ID = 7;

SELECT * FROM Demo WHERE Name LIke '%SQL%';
SELECT Name FROM Demo ORDER BY Hint DESC;
